<h1 align="center">Лабораторна робота №5<br>Основи роботи з бібліотекою NumPy</h1>

***<center>Сухонос Вероніка, КН-423к</center>***

**Мета роботи:** отримати базові знання та навички щодо роботи з бібліотекою NumPy в мові програмування Python.

## Варіант

In [3]:
N = ord('V') % 15 + 1
print(f'Варіант №{N}')

Варіант №12


In [4]:
import numpy as np
from time import perf_counter as timer
import random

## Завдання 1

Виконати набір вправ. Всі завдання виконати 2 способами:
  * з використанням універсальних функцій бібліотеки NumPy
  * за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)

Для обох випадків підрахувати час виконання скрипту та зробити висновок.

**Номери вправ для виконання**: 2, 3, 5, 14, 17, 18, 19, 20, 21.

### Визначення допоміжних функцій для порівняння часу виконання скриптів та форматування виводу списків

In [7]:
NP, IT = 'np', 'it'
time = {}

def compare_time():
  n, i = time[NP], time[IT]

  res = 'Conclusion: NumPy functions were '
  if (np.allclose(n, i)):
    res += 'AS effective as '
  elif (n < i):
    res += 'MORE effective than '
  elif (n > i):
    res += 'LESS effective than '
  res += f'pure Python iteractive constructions (diff = {abs(n - i)} s)'

  print(f'\nExecution time: NumPy = {n} s, pure Python = {i} s')
  print(res)

def print_l(l):
  N = len(l)

  if (N > 0 and type(l[0]) == list):
    for i in range(N):
      print(f"{'[' if i == 0 else ' '}{l[i]}{']' if i == N - 1 else ''}")
  else:
    print(l)

### Вправа 2

Вводиться число `n`. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром `n` на `n`, використовуючи слайсинг.

In [9]:
def task2_np(n):
  s = timer()

  matrix = np.ones((n, n))
  matrix[1::2, 0::2] = 0
  matrix[0::2, 1::2] = 0

  time[NP] = timer() - s
  print(matrix)


def task2_it(n):
  s = timer()

  matrix = [[1 for _ in range(n)] for _ in range(n)]
  for row in range(n):
    matrix[row][(row % 2 == 0)::2] = [0] * len(matrix[row][(row % 2 == 0)::2])

  time[IT] = timer() - s
  print_l(matrix)


task2_np(5)
print()
task2_it(5)
compare_time()

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]

[[1, 0, 1, 0, 1]
 [0, 1, 0, 1, 0]
 [1, 0, 1, 0, 1]
 [0, 1, 0, 1, 0]
 [1, 0, 1, 0, 1]]

Execution time: NumPy = 4.210002953186631e-05 s, pure Python = 1.4999997802078724e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 2.7100031729787588e-05 s)


### Вправа 3

Вводяться 4 числа  `n`, `m`, `r`, `c`. Вивести масив розміру `n` на `m`, в якому в кожному `r`-му рядку і в кожному `c`-му стовпчику стоять 0, а інші елементи дорівнюють 1.

In [11]:
def task3_np(n, m, r, c):
  s = timer()

  matrix = np.ones((n, m))
  matrix[::r] = 0
  matrix[::, ::c] = 0

  time[NP] = timer() - s
  print(matrix)


def task3_it(n, m, r, c):
  s = timer()

  matrix = [[0 if (i % r == 0 or j % c == 0) else 1 for j in range(m)] for i in range(n)]

  time[IT] = timer() - s
  print_l(matrix)


task3_np(6, 7, 2, 3)
print()
task3_it(6, 7, 2, 3)
compare_time()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]]

[[0, 0, 0, 0, 0, 0, 0]
 [0, 1, 1, 0, 1, 1, 0]
 [0, 0, 0, 0, 0, 0, 0]
 [0, 1, 1, 0, 1, 1, 0]
 [0, 0, 0, 0, 0, 0, 0]
 [0, 1, 1, 0, 1, 1, 0]]

Execution time: NumPy = 4.1599967516958714e-05 s, pure Python = 1.1599971912801266e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 2.9999995604157448e-05 s)


### Вправа 5

Вводиться число `n`. Вивести масив розміру `n` на `n`, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [13]:
def task5_np(n):
  s = timer()

  matrix = np.zeros((n, n))
  matrix[::2] = 1

  time[NP] = timer() - s
  print(matrix)


def task5_it(n):
  s = timer()

  matrix = [[1 if i % 2 == 0 else 0 for _ in range(n)] for i in range(n)]

  time[IT] = timer() - s
  print_l(matrix)


task5_np(5)
print()
task5_it(5)
compare_time()

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]

[[1, 1, 1, 1, 1]
 [0, 0, 0, 0, 0]
 [1, 1, 1, 1, 1]
 [0, 0, 0, 0, 0]
 [1, 1, 1, 1, 1]]

Execution time: NumPy = 1.9700033590197563e-05 s, pure Python = 9.100011084228754e-06 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 1.0600022505968809e-05 s)


### Вправа 14

Розмістити на полі 8х8 нулі та одиниці в шахматному порядку, використовуючи функцію `numpy.tile()`.

In [15]:
N = 8

def task14_np():
  s = timer()

  matrix = np.tile(np.array([[0, 1], [1, 0]]), (int(N / 2), int(N / 2)))

  time[NP] = timer() - s
  print(matrix)


def task14_it():
  s = timer()

  matrix = [[0 for _ in range(N)] for _ in range(N)]
  for row in range(N):
    matrix[row][(row % 2 == 0)::2] = [1] * len(matrix[row][(row % 2 == 0)::2])

  time[IT] = timer() - s
  print_l(matrix)


task14_np()
print()
task14_it()
compare_time()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0, 1, 0, 1, 0, 1, 0, 1]
 [1, 0, 1, 0, 1, 0, 1, 0]
 [0, 1, 0, 1, 0, 1, 0, 1]
 [1, 0, 1, 0, 1, 0, 1, 0]
 [0, 1, 0, 1, 0, 1, 0, 1]
 [1, 0, 1, 0, 1, 0, 1, 0]
 [0, 1, 0, 1, 0, 1, 0, 1]
 [1, 0, 1, 0, 1, 0, 1, 0]]

Execution time: NumPy = 9.139999747276306e-05 s, pure Python = 2.039998071268201e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 7.100001676008105e-05 s)


### Вправа 17

Заповнити вектор значеннями від 0 до `n`. Замінити знаки для всіх значень, що менші за `n/2` та більші за `3n/4`, на протилежні.

In [17]:
def task17_np(n):
  s = timer()

  vector = np.arange(n + 1)
  vector = np.where((vector < (n / 2)) | (vector > (3 * n / 4)), -vector, vector)

  time[NP] = timer() - s
  print(vector)


def task17_it(n):
  s = timer()

  vector = [i if (n / 2) <= i <= (3 * n / 4) else -i for i in range(n + 1)]

  time[IT] = timer() - s
  print_l(vector)


task17_np(10)
print()
task17_it(10)
compare_time()

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]

[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]

Execution time: NumPy = 0.00011629995424300432 s, pure Python = 7.599999662488699e-06 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 0.00010869995458051562 s)


### Вправа 18

Згенерувати вектор з `n` випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [19]:
LOW, HIGH = 0, 99

def task18_np(n):
  s = timer()

  vector = np.random.randint(LOW, HIGH, n)
  unique = np.unique(vector)

  time[NP] = timer() - s
  print(f'In sequence {vector} - {unique.size} unique numbers')


def task18_it(n):
  s = timer()

  vector = [random.randint(LOW, HIGH) for _ in range(n)]
  unique = []
  for num in vector:
    if num not in unique:
      unique.append(num)

  time[IT] = timer() - s
  print(f'In sequence {vector} - {len(unique)} unique numbers')


task18_np(30)
print()
task18_it(30)
compare_time()

In sequence [74 64 64 89 60 50 12 57 66  3 70 31 47 88 94 30 63 15 75 57 35 83 31 20
  7 21 95 87 57 44] - 26 unique numbers

In sequence [59, 36, 45, 27, 62, 82, 74, 43, 17, 2, 58, 22, 41, 5, 51, 22, 55, 33, 59, 80, 4, 33, 27, 63, 73, 52, 23, 89, 18, 2] - 25 unique numbers

Execution time: NumPy = 0.00019990000873804092 s, pure Python = 5.909998435527086e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 0.00014080002438277006 s)


### Вправа 19

Згенерувати вектор із `n` елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.

In [21]:
LOW, HIGH = 0, 1

def task19_np(n):
  s = timer()

  vector = np.round(np.linspace(LOW, HIGH, n + 2)[1:-1], 3)

  time[NP] = timer() - s
  print(vector)


def task19_it(n):
  s = timer()

  step = (HIGH - LOW) / (n + 1)
  vector = [round(LOW + step * i, 3) for i in range(1, n + 1)]

  time[IT] = timer() - s
  print(vector)


task19_np(10)
print()
task19_it(10)
compare_time()

[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]

[0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]

Execution time: NumPy = 0.00031100003980100155 s, pure Python = 2.110004425048828e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 0.00028989999555051327 s)


### Вправа 20

Згенерувати вектор із `n` випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [23]:
def task20_np(n):
  s = timer()

  init_vector = np.random.random(n)
  res_vector = np.where(init_vector == np.max(init_vector), 0, init_vector)

  time[NP] = timer() - s
  print(f'Initial vector: {init_vector}')
  print(f'Changed vector: {res_vector}')


def task20_it(n):
  s = timer()

  init_vector = [random.random() for _ in range(n)]
  max_num = init_vector[0]
  for num in init_vector:
    if num > max_num:
      max_num = num
  res_vector = [0 if num == max_num else num for num in init_vector]

  time[IT] = timer() - s
  print(f'Initial vector: {init_vector}')
  print(f'Changed vector: {res_vector}')


task20_np(5)
print()
task20_it(5)
compare_time()

Initial vector: [0.36259046 0.83736174 0.11866086 0.19843462 0.88059943]
Changed vector: [0.36259046 0.83736174 0.11866086 0.19843462 0.        ]

Initial vector: [0.37639518659765536, 0.04999710651008382, 0.21992390735658507, 0.9550792065142135, 0.39160818116941554]
Changed vector: [0.37639518659765536, 0.04999710651008382, 0.21992390735658507, 0, 0.39160818116941554]

Execution time: NumPy = 0.00010269996710121632 s, pure Python = 8.100003469735384e-06 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 9.459996363148093e-05 s)


### Вправа 21

Ввести числа `n` і `m`. Згенерувати матрицю `n` на `n` випадкових цілих елементів з діапазону `[0, m]`. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [25]:
def task21_np(n, m):
  s = timer()

  init_matrix = np.random.randint(0, m + 1, (n, n))
  max_num = np.max(init_matrix)
  res_matrix = np.where(init_matrix == max_num, -init_matrix, init_matrix)

  time[NP] = timer() - s
  print(f'Initial matrix:\n {init_matrix}')
  print(f'Changed matrix:\n {res_matrix}')


def task21_it(n, m):
  s = timer()

  init_matrix = [[random.randint(0, m) for _ in range(n)] for _ in range(n)]
  max_num = init_matrix[0][0]
  for row in init_matrix:
    for num in row:
      if num > max_num:
        max_num = num
  res_matrix = [[-num if num != max_num else num for num in row] for row in init_matrix]

  time[IT] = timer() - s
  print(f'Initial matrix:')
  print_l(init_matrix)
  print(f'Changed matrix:')
  print_l(res_matrix)


task21_np(4, 10)
print()
task21_it(4, 10)
compare_time()

Initial matrix:
 [[ 7 10  7  6]
 [ 6 10  7  0]
 [ 5  5 10  8]
 [ 8 10  8  8]]
Changed matrix:
 [[  7 -10   7   6]
 [  6 -10   7   0]
 [  5   5 -10   8]
 [  8 -10   8   8]]

Initial matrix:
[[7, 4, 2, 1]
 [2, 5, 6, 4]
 [10, 2, 1, 4]
 [7, 9, 4, 2]]
Changed matrix:
[[-7, -4, -2, -1]
 [-2, -5, -6, -4]
 [10, -2, -1, -4]
 [-7, -9, -4, -2]]

Execution time: NumPy = 0.0001303000026382506 s, pure Python = 7.400003960356116e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 5.6299963034689426e-05 s)


## Завдання 2

Розв’язати систему лінійних алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
  * матричного множення
  * оберненої матриці
  * функції `numpy.linalg.solve()`

Порівняти всі рішення за допомогою функції `numpy.allclose()`.

**Дана система рівнянь**:

$$
\begin{cases}
x_{1} + x_{2} - x_{3} - x_{4} = 0 \\
x_{2} + 2x_{3} - x_{4} = 2 \\
x_{1} - x_{2} - x_{4} = -1 \\
- x_{1} + 3x_{2} - 2x_{3} = 0
\end{cases}
$$

### Розв'язання СЛАР за формулами Крамера

In [28]:
A = np.array([
  [1, 1, -1, -1],
  [0, 1, 2, -1],
  [1, -1, 0, -1],
  [-1, 3, -2, 0]
])

B = np.array([0, 2, -1, 0])

def cramer(A, B):
  det = np.linalg.det(A)

  if (det == 0):
    raise ValueError("Matrix of coefficients A has a zero determinant. Cannot use the Cramer's rule.")

  N, X = len(A), []

  for col in range(N):
    tmp = [[A[i][j] if j != col else B[i] for j in range(N)] for i in range(N)]
    tmp_det = np.linalg.det(tmp)
    X.append(round(tmp_det / det, 10))
  return X

X = cramer(A, B)
print("Solution vector X obtained using the Cramer's rule:", X)

Solution vector X obtained using the Cramer's rule: [1.0, 1.0, 1.0, 1.0]


### Перевірка знайденого розв’язку

In [30]:
B_mult = A.dot(X)
print('Vector of free terms B_mult obtained by mutiplying matrix of coefficients A by X:', B_mult)
print('Vector of free terms B equals B_mult:', np.allclose(B, B_mult))

print()

X_inv = np.linalg.inv(A).dot(B)
print("Solution vector X_inv obtained by multiplying inversed matrix A⁻¹ by B:", X)
print("Solution vector X equals X_inv:", np.allclose(X, X_inv))

print()

X_np = np.linalg.solve(A, B)
print("Solution vector X_np obtained by using a dedicated NumPy function:", X_np)
print("Solution vector X equals X_np:", np.allclose(X, X_np))

Vector of free terms B_mult obtained by mutiplying matrix of coefficients A by X: [ 0.  2. -1.  0.]
Vector of free terms B equals B_mult: True

Solution vector X_inv obtained by multiplying inversed matrix A⁻¹ by B: [1.0, 1.0, 1.0, 1.0]
Solution vector X equals X_inv: True

Solution vector X_np obtained by using a dedicated NumPy function: [1. 1. 1. 1.]
Solution vector X equals X_np: True


## Завдання 3

Обчислити значення матричного виразу 2 способами:
  * з використанням універсальних функцій бібліотеки NumPy
  * за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)

Порівняти всі рішення за допомогою функції `numpy.allclose()`.

Для обох випадків підрахувати час виконання скрипту та зробити висновок.

**Даний матричний вираз**:

$$
A(A^{2} - B) - 2(B + A)B\text{, де }
A =
\begin{pmatrix}
2 & 3 & 1 \\
-1 & 2 & 4 \\
5 & 3 & 0
\end{pmatrix}
B =
\begin{pmatrix}
2 & 7 & 13 \\
-1 & 0 & 5 \\
5 & 13 & 21
\end{pmatrix}
$$

In [32]:
A = [
  [2, 3, 1],
  [-1, 2, 4],
  [5, 3, 0]
]

B = [
  [2, 7, 13],
  [-1, 0, 5],
  [5, 13, 21]
]

def solve_matrix_expression_np(A, B):
  s = timer()

  res = np.subtract(np.dot(A, np.subtract(np.dot(A, A), B)), np.dot(np.multiply(np.add(B, A), 2), B))
  # res = A @ (A @ A - B) - 2 * (B + A) @ B

  time[NP] = timer() - s
  print(f'Result of the matrix expression using NumPy functions:\n{res}')
  return res

def mult_m(m1, m2):
  m1_rows, m1_cols, m2_rows, m2_cols = len(m1), len(m1[0]), len(m2), len(m2[0])

  if m1_cols != m2_rows:
    raise ValueError('Number of columns in the 1st matrix must equal number of rows in the 2nd matrix for multiplication.')

  res = [[0] * m2_cols for _ in range(m1_rows)]

  for i in range(m1_rows):
    for j in range(m2_cols):
      for k in range(m2_rows):
        res[i][j] += m1[i][k] * m2[k][j]
  return res

def add_m(m1, m2, add=True):
  m1_rows, m1_cols, m2_rows, m2_cols = len(m1), len(m1[0]), len(m2), len(m2[0])

  if not (m1_rows == m1_cols == m2_rows == m2_cols):
    raise ValueError('Matrices must have equal dimensions for addition.')

  res = [[0] * m1_rows for _ in range(m1_rows)]

  for i in range(m1_rows):
    for j in range(m2_cols):
      res[i][j] = m1[i][j] + m2[i][j] if add else m1[i][j] - m2[i][j]
  return res

def mult_m_by_num(m, num):
  m_rows, m_cols = len(m), len(m[0])

  res = [[0] * m_rows for _ in range(m_rows)]

  for i in range(m_rows):
    for j in range(m_cols):
      res[i][j] = m[i][j] * num
  return res

def solve_matrix_expression_it(A, B):
  s = timer()

  res = add_m(mult_m(A, add_m(mult_m(A, A), B, False)), mult_m(mult_m_by_num(add_m(B, A), 2), B), False)

  time[IT] = timer() - s
  print('Result of the matrix expression using pure Python iterative constructions:')
  print_l(res)
  return res

res_np = solve_matrix_expression_np(np.array(A), np.array(B))
print()
res_it = solve_matrix_expression_it(A, B)

print('\nResults are equal:', np.allclose(res_np, res_it))
compare_time()

Result of the matrix expression using NumPy functions:
[[  -75  -357  -788]
 [  -40  -156  -359]
 [ -147  -607 -1291]]

Result of the matrix expression using pure Python iterative constructions:
[[-75, -357, -788]
 [-40, -156, -359]
 [-147, -607, -1291]]

Results are equal: True

Execution time: NumPy = 7.890001870691776e-05 s, pure Python = 6.54000323265791e-05 s
Conclusion: NumPy functions were LESS effective than pure Python iteractive constructions (diff = 1.3499986380338669e-05 s)
